[package]
name = "safe-gc"
version = "0.1.0"
authors = [""]
edition = "2018"


[lib]
name = "safe_gc"

[features]
#derive = ["safe_gc_derive"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
safe_gc_derive = {path="gc-macro"}
